alias grunt="node_modules/grunt-cli/bin/grunt"
alias redis.server="redis-server /usr/local/etc/redis.conf --daemonize yes"
alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"
alias rm="rm -v $1"
alias proxy="ssh -Nv deploy@server.com -D 8080"
alias router="ssh root@192.168.1.1"
